### PR TITLE
Track app downloads by country

### PR DESCRIPTION
**Pull request by razzeee**

### CODE REVIEW

**Comment by ramcq** [comment]
I think adding "country" into the dictionary of arches probably constitutes an interface break which might stop parsers from working if they are iterating that list expecting each key to be an arch - it seems a bit magic. Perhaps we can set up a new top-level ref_by_country key which is just { ref -> { XX: 1, YY: 2, ... }, ... } - maybe also not bothering to distinguish upgrades from installs?

**Comment by ramcq** [comment]
(Also thanks for working on this, we could do a super cool map colouring visualisation on the website. :D)

**Comment by razzeee** [comment]
Agreed, it kind of was a bad desgin already, the arches should have been in a dict named that. But probably a good idea, to not break the format there.

The website part should basically just be able to reuse the code we already have for the statistics page worldmap.

**Comment by razzeee** [comment]
Updated accordingly

**Pull request merged**
